# Generated by Django 5.1.15 on 2026-07-22 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('business_phone', models.CharField(max_length=32)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounts.accountprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=100)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('national_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_representative_name', models.CharField(max_length=255)),
                ('legal_representative_national_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='marketplace.store')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.devicevariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'device_variant'), name='unique_store_device_variant_offer'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='offer_price_positive'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='offer_quantity_nonnegative')],
            },
        ),
    ]
