# Generated by Django 6.0.7 on 2026-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_checkoutattempt'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'refund')), fields=('order', 'transaction_type'), name='unique_order_refund_transaction'),
        ),
    ]
