# Generated by Django 6.0.2 on 2026-07-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=500)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('schema_version', models.CharField(default='clean-data-v1', max_length=50)),
                ('importer_version', models.CharField(default='1.0', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_imported', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('records_skipped', models.PositiveIntegerField(default=0)),
                ('validation_messages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_key', models.SlugField(allow_unicode=True, max_length=300)),
                ('device_kind', models.CharField(choices=[('smartphone', 'Smartphone'), ('feature_phone', 'Feature phone'), ('tablet', 'Tablet'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('announced_on', models.DateField(blank=True, null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_catalog_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='catalog.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectivitySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports_5g', models.BooleanField(blank=True, null=True)),
                ('wifi_standard', models.CharField(blank=True, max_length=30, null=True)),
                ('bluetooth_version', models.CharField(blank=True, max_length=20, null=True)),
                ('supports_nfc', models.BooleanField(blank=True, null=True)),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_spec', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CameraSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('rear', 'Rear'), ('front', 'Front')], max_length=10)),
                ('max_video_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('max_video_fps', models.PositiveIntegerField(blank=True, null=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_systems', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BatterySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_mah', models.PositiveIntegerField(blank=True, null=True)),
                ('wired_charging_w', models.PositiveIntegerField(blank=True, null=True)),
                ('supports_wireless_charging', models.BooleanField(blank=True, null=True)),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battery_spec', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_technology', models.CharField(blank=True, max_length=120, null=True)),
                ('sku_or_region', models.CharField(blank=True, max_length=120, null=True)),
                ('configuration_key', models.CharField(max_length=400)),
                ('is_available', models.BooleanField(default=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DisplaySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('cover', 'Cover'), ('external', 'External'), ('unknown', 'Unknown')], default='primary', max_length=20)),
                ('size_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resolution_width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=120, null=True)),
                ('refresh_rate_hz', models.PositiveIntegerField(blank=True, null=True)),
                ('peak_brightness_nits', models.PositiveIntegerField(blank=True, null=True)),
                ('supports_hdr', models.BooleanField(blank=True, null=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_specs', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu_description', models.TextField(blank=True, null=True)),
                ('gpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_spec', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_spec', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_version', models.PositiveIntegerField(blank=True, null=True)),
                ('promised_major_updates', models.PositiveIntegerField(blank=True, null=True)),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_spec', to='catalog.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField()),
                ('normalized_payload', models.JSONField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_history', models.JSONField(blank=True, default=list)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('rejected', 'Rejected'), ('ambiguous', 'Ambiguous')], default='valid', max_length=20)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_records', to='catalog.datasource')),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='catalog.devicemodel')),
                ('first_import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_source_records', to='catalog.importrun')),
                ('last_import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_source_records', to='catalog.importrun')),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalFieldEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=255)),
                ('observed_value', models.JSONField()),
                ('confidence', models.CharField(choices=[('source_normalized', 'Source-normalized'), ('ambiguous', 'Ambiguous')], max_length=30)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_evidence', to='catalog.devicemodel')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_evidence', to='catalog.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='BenchmarkMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_name', models.CharField(max_length=80)),
                ('benchmark_version', models.CharField(blank=True, max_length=40, null=True)),
                ('measurement_key', models.CharField(max_length=160)),
                ('score', models.PositiveIntegerField()),
                ('measured_at', models.DateField(blank=True, null=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benchmark_measurements', to='catalog.devicemodel')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_measurements', to='catalog.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='CameraLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('wide', 'Wide'), ('ultrawide', 'Ultrawide'), ('telephoto', 'Telephoto'), ('macro', 'Macro'), ('depth', 'Depth'), ('unknown', 'Unknown')], max_length=20)),
                ('megapixels', models.PositiveIntegerField(blank=True, null=True)),
                ('has_ois', models.BooleanField(blank=True, null=True)),
                ('camera_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenses', to='catalog.camerasystem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('camera_system', 'role'), name='unique_camera_lens_role')],
            },
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'model_key'), name='unique_brand_model_key'),
        ),
        migrations.AddConstraint(
            model_name='camerasystem',
            constraint=models.UniqueConstraint(fields=('device_model', 'position'), name='unique_camera_position'),
        ),
        migrations.AddConstraint(
            model_name='devicevariant',
            constraint=models.UniqueConstraint(fields=('device_model', 'configuration_key'), name='unique_variant_configuration'),
        ),
        migrations.AddConstraint(
            model_name='devicevariant',
            constraint=models.CheckConstraint(condition=models.Q(('storage_gb__isnull', True), ('storage_gb__gte', 1), _connector='OR'), name='variant_storage_positive'),
        ),
        migrations.AddConstraint(
            model_name='devicevariant',
            constraint=models.CheckConstraint(condition=models.Q(('ram_gb__isnull', True), ('ram_gb__gte', 1), _connector='OR'), name='variant_ram_positive'),
        ),
        migrations.AddConstraint(
            model_name='displayspec',
            constraint=models.UniqueConstraint(fields=('device_model', 'role'), name='unique_display_role'),
        ),
        migrations.AddConstraint(
            model_name='displayspec',
            constraint=models.CheckConstraint(condition=models.Q(('size_inches__isnull', True), ('size_inches__gt', 0), _connector='OR'), name='display_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='sourcerecord',
            constraint=models.UniqueConstraint(fields=('data_source', 'source_url'), name='unique_source_identity'),
        ),
        migrations.AddConstraint(
            model_name='canonicalfieldevidence',
            constraint=models.UniqueConstraint(fields=('device_model', 'field_path', 'source_record'), name='unique_field_evidence_per_source'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkmeasurement',
            constraint=models.UniqueConstraint(fields=('device_model', 'source_record', 'measurement_key'), name='unique_benchmark_measurement'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='benchmark_score_nonnegative'),
        ),
    ]
