# Generated by Django 6.0.2 on 2026-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_userqueryset'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
