# Generated by Django 6.0.7 on 2026-07-25 16:16

from datetime import timedelta

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_checkoutattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='expires_at',
            field=models.DateTimeField(
                db_index=True,
                default=timezone.now() + timedelta(minutes=30),
            ),
        ),
    ]
