# Generated by Django 6.0.7 on 2026-07-25

from django.db import migrations, models

from shopping.models import basket_reservation_deadline


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0004_basketitem_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="expires_at",
            field=models.DateTimeField(
                default=basket_reservation_deadline,
                db_index=True,
            ),
        ),
    ]
